language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - "if [ $TRAVIS_OS_NAME = 'osx' ] && [ $CC = 'gcc' ]; then export CC=gcc-4.8; fi"
  - "if [ $TRAVIS_OS_NAME = 'osx' ]; then brew update && brew install qt && brew install protobuf; fi"

addons:
  apt:
    packages:
      - libqt4-dev
      - qt4-qmake
      - libpcap-dev
      - libprotobuf-dev
      - protobuf-compiler

script:
  - qmake
  - make

